version: 2
jobs:
  build:
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Transfer Files
          command: |
            scp ./bot.js $USERNAME@$SERVER:/home/marv/
            scp ./package.json $USERNAME@$SERVER:/home/marv/
      - run:
          name: Deploy
          command: |
            ssh -t $USERNAME@$SERVER "/home/marv/deploy.sh"
